hydra:
  run:
    dir: exp_output/${now:%Y.%m.%d}/test_${now:%H%M%S}
  sweep:
    dir: exp_output/${now:%Y.%m.%d}/${now:%H%M%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - agent=prompts_llm
    - use_threadpool=False
    - tp_max_workers=32
    - num_trials=32
    - max_actions_per_trial=32
    - env_kwargs.rule=conjunctive,disjunctive
    - env_kwargs.num_objects=8,4
    - env_kwargs.num_blickets=2
    - env_kwargs.transition_noise=0.0
    - agent.model=ollama/gemma3:12b
    - agent.temperature=0.0
    - agent.react=False
    - agent.system_msg_path=./agent/prompts/system_human_conj.txt
    - seed=22
  job:
    name: run_trials_blicket
    chdir: true
    override_dirname: agent.model=ollama/gemma3:12b,agent.react=False,agent.system_msg_path=./agent/prompts/system_human_conj.txt,agent.temperature=0.0,agent=prompts_llm,env_kwargs.num_blickets=2,env_kwargs.num_objects=8,4,env_kwargs.rule=conjunctive,disjunctive,env_kwargs.transition_noise=0.0,max_actions_per_trial=32,num_trials=32,seed=22,tp_max_workers=32,use_threadpool=False
    id: ???
    num: ???
    config_name: run_trials_blicket
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /home/anthony/Project/rl-scm-tests/blicket_text
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/anthony/Project/rl-scm-tests/blicket_text
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      agent: prompts_llm
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
agent:
  _target_: agent.prompts_llm.PromptsAgent
  _recursive_: false
  horizon: ${max_actions_per_trial}
  filter_actions: false
  react: false
  model: ollama/gemma3:12b
  temperature: 0.0
  system_msg_path: ./agent/prompts/system_human_conj.txt
num_trials: 32
max_actions_per_trial: 32
save_trial_log: true
use_threadpool: false
tp_max_workers: 32
seed: 22
env_kwargs:
  num_objects: 4
  num_blickets: 2
  init_prob: 0.1
  transition_noise: 0.0
  rule: conjunctive
